### ISSUE TITLE
Dynamic Bottom Sheet height based on Children height

### ISSUE THREAD

**Issue by SatyaFariz** [gorhom/react-native-bottom-sheet#32]
# Feature Request

It would be awesome if you add dynamic height feature based on the children height (and still able to define max height of the bottom sheet). Also the snapPoints prop should be relative to the total Bottom Sheet height, not the screen height.

## Why it is needed

Sometimes we only need to render only a few items inside the bottom sheet. So there's no need to define the bottom sheet height. It should adjust itself according to the children height. And the snapPoints should be relative to the height of the bottom sheet, not the screen height like in the example.

**Comment by gorhom** [comment]
hi @SatyaFariz , thanks for submitting this feature request, i will pick it up as soon as i get free 👍

**Comment by sa8ab** [comment]
This is a good one.

**Comment by EricPKerr** [comment]
Another similar enhancement would be to allow the snapPoints to change (with something like an onLayout callback) and then have the sheet handle animating to the new position

**Comment by mrmarktyy** [comment]
I have sort of a singleton Bottom Sheet component and `snapPoints` prop is a local state.
Depends on the use cases, I'd update `snapPoints` before expand the bottom sheet, But i found it is somehow problematic ?

So I am wondering whether dynamic `snapPoints` is supported ?

**Comment by fabcall** [comment]
@mrmarktyy I've managed to get it working by setting a key prop to BottomSheet component. So, when it's children view is indeed calculated, it invalidates the layout:

```
<BottomSheet
      ref={sheetRef}
      initialSnapIndex={0}
      snapPoints={snapPoints}
      topInset={StatusBar.currentHeight}
      key={layout.measured.toString()}>
    {{ children }}
</BottomSheet>
```

**Comment by mrmarktyy** [comment]
Thanks @fabcall good one, i'll give it try.
I actually ended up getting it work with a hacky setTimeout after updating `snapPoints`, I guess it worked because timeout gives the react to recalculate the new layout, etc.

**Comment by EricPKerr** [comment]
The only issue is that it goes instantly to the new point instead of animating there.  It would be nice to have the `useTransition` internal hook find the closest new snapPoint when those change and update the position via transition (or have that be an available prop option).

**Comment by gorhom** [comment]
my initial idea is to add a new value type `auto` to `snapPoints`, which will measure content height and uses it value as a snap point before animating.

i'll look into it this weekend :)

**Comment by fabcall** [comment]
@gorhom sounds nice to me. Keep in mind that, if content height is bigger than screen, you could replace "auto" with "100%" and keep the default behavior ;)

**Comment by gorhom** [comment]
hi guys @SatyaFariz, @EricPKerr, @fabcall, @mrmarktyy 

i have submitted a draft pr for this feature and while i finish it up, i would appreciate if you could test it

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#feature/dynamic-snap-point
```

## Sample Code
```tsx
/* eslint-disable react-native/no-inline-styles */
import React, { useMemo, useRef } from 'react';
import { View, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const BasicExample = () => {
  // hooks
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => [100, 200], []);

  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        initialSnapIndex={0}
        shouldMeasureContentHeight={true} // < new prop 🔥
      >
        <View
          style={{
            height: 500,
            backgroundColor: 'white',
          }}
        />
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    height: 500,
    backgroundColor: 'white',
  },
});

export default BasicExample;

```

**Comment by avet-m** [comment]
@gorhom thank you
it works perfect on static view but seems like there are some problem with scrollable components like BottomSheetScrollView, the bottom sheet doesn't reach last point, just jumping up and down 

**Code example**
```

import React, { useMemo, useRef } from 'react';
import { View, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const BasicExample = () => {
  // hooks
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => [100, 200], []);

  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        initialSnapIndex={0}
        shouldMeasureContentHeight={true} // < new prop 🔥
      >
       <BottomSheetScrollView>
          <View
            style={{
              height: 500,
              backgroundColor: 'white',
            }}
          />
        </BottomSheetScrollView>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    height: 500,
    backgroundColor: 'white',
  },
});

export default BasicExample;
```

**Comment by gorhom** [comment]
thanks @avet-m for spotting this issue,, i have pushed the fix already, please try again and let me know.

⚠️ you will need to reinstall the branch again:

```bash
yarn add ssh://git@github.com:gorhom/react-native-bottom-sheet#feature/dynamic-snap-point
```

**Comment by avet-m** [comment]
@gorhom now the scroll of `BottomSheetScrollView` doesn't work, and also it doesn't work with `shouldMeasureContentHeight={flase}`

**Comment by fabcall** [comment]
@gorhom using `useBottomSheetModal` also shows an erratic behavior. For instance, 

```
presentPasswordRecovery(
    <PasswordRecovery dismissPasswordRecovery={dismissPasswordRecovery} />,
    {
      animationDuration: 300,
      animatedPosition: snapPoints.passwordRecovery,
      handleComponent: Grabber,
      snapPoints: [20],
      shouldMeasureContentHeight: true,
    },
  );
```
will show the component at the specified point (20). Even though you can drag it up to its measured height, it animates back to point 20.

**Comment by gorhom** [comment]
a quick update, managed to get `snapPoints` to be reactive, so the sheet will listen to all its updates. 

[here is a preview](https://twitter.com/gorhom/status/1328824557734682630)

**Comment by fabcall** [comment]
This ia simply beautiful 😍. Amazing work, @gorhom

**Comment by gorhom** [comment]
quick update:

- Because of the complexity of implementing this feature and other breaking changes, it will be released with the next major release v2.0 along with the reanimated v2 version.
- Current implementation works perfectly with `BottomSheetView`, however it could works with `Scrollable` but with more extra steps, since `VirtualizedList` items height is unpredictable.
- I am working now im cleaning up this PR - only for `BottomSheetView` - and will post it here so you guys can test it and then i'll start preparing for the release v2.0.

i can't promise a specific date,, but i will try my best to get out asap :)

**Comment by sa8ab** [comment]
I've used other web development frameworks and I think this feature is something none of them have met so far :D

**Comment by gorhom** [comment]
hi there 👋

here is a final pr to test this feature: https://github.com/gorhom/react-native-bottom-sheet/pull/81

**Comment by gorhom** [comment]
I just pushed an alpha release for v2, please try it and let me know :)

also check out the new [documents website ( still in progress )](https://gorhom.github.io/react-native-bottom-sheet/) 🎉

```bash
yarn add @gorhom/bottom-sheet@2.0.0-alpha.2
```

**Comment by nandorojo** [comment]
Hey @gorhom is this available in v2? I don't see it on the docs. Thanks!

**Comment by gorhom** [comment]
@nandorojo yes! it is available for `v2` & `v3`, look at the example  [Dynamic Snap Point Example](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/DynamicSnapPointExample.tsx).

**Comment by dorw123** [comment]
Still not working for BottomSheetScrollView? 
onContentSizeChange not fireing at all, onLayout only fires on the first render.

**Comment by ngoel37** [comment]
Hey there - I may be totally missing something on the example @gorhom, but is contentHeight being set when the size of the content changes? As far as I can tell, onLayout only fires on the first render, not when the content size changes.

**Comment by Isaacmeedinaa** [comment]
@gorhom Thank you very much for this fix... I would like to point out 2 issues with dynamic heights.

1. There isn't an "out-of-the-box" fix to set a height limit. I had to do it with Dimensions.
2. This is one is the important... Scrollables are still not working with dynamic heights. Will there be a fix for this soon? Thanks!

**Comment by VladSenko** [comment]
@gorhom  I have BottomSheet with dynamic height content inside. This content is actually a separate component that shows some data. I set this data by clicking on an element outside the bottom sheet and then open the bottom sheet. Dynamic height is calculated but BottomSheet behaves very oddly: it jumps up/down or even closes immediately after content height change.

Please help.

**Comment by anhquan291** [comment]
> @gorhom I have BottomSheet with dynamic height content inside. This content is actually a separate component that shows some data. I set this data by clicking on an element outside the bottom sheet and then open the bottom sheet. Dynamic height is calculated but BottomSheet behaves very oddly: it jumps up/down or even closes immediately after content height change.
> 
> Please help.

I'm also facing the problem(v3). The bottom sheet goes down immediately when calculating the new height. Please help. Thanks

**Comment by VKBobyr** [comment]
I know this is a bit of a code dump, but I was able to achieve this by measuring the size of the child, calculating how big it is compared to the rest of the screen, and setting the size of the Draggable sheet.

Warning: very hacky
```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

Future<void> showAesDraggableBottomSheet({
  required BuildContext context,
  required AesDraggableBottomSheet sheet,
}) {
  return showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (c) => sheet,
  );
}

class AesDraggableBottomSheet extends HookWidget {
  final Widget child;
  final double childHeightPercentage;
  final bool omitScrollview;
  final EdgeInsets padding;
  final Color bgColor;

  AesDraggableBottomSheet({
    required this.child,
    this.childHeightPercentage = 1,
    this.omitScrollview = false,
    this.bgColor = Colors.white,
    this.padding = const EdgeInsets.only(
      top: 25,
      left: 15,
      right: 15,
    ),
  });

  @override
  Widget build(BuildContext context) {
    final height = useState(0.0);

    Widget makeDismissable({required Widget child}) => GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () => Navigator.of(context).pop(),
          child: GestureDetector(
            child: child,
            onTap: () {},
          ),
        );

    // used to measure child height
    final _child = SingleChildScrollView(
      child: MeasuredWidget(
        onCalculateSize: (v) => height.value = v!.height,
        child: child,
      ),
    );

    // calculate the proportion
    final maxSize = useMemoized(
      () => ((height.value + 50) / MediaQuery.of(context).size.height)
          .clamp(.1, .9),
      [height.value],
    );

    // for some reason initSize can't equal max size for very long widgets
    final initSize = maxSize * (childHeightPercentage - .0001);

    print("$maxSize $initSize");

    // render the child to get its height
    if (height.value == 0) {
      return _child;
    }

    // use the height to generate a bottom sheet
    return makeDismissable(
      child: DraggableScrollableSheet(
        maxChildSize: maxSize,
        minChildSize: initSize,
        initialChildSize: initSize,
        builder: (context, controller) {
          return Material(
            borderRadius: BorderRadius.circular(20),
            color: bgColor,
            child: ListView(
              padding: EdgeInsets.all(10),
              controller: controller,
              children: [_child],
            ),
          );
        },
      ),
    );
  }
}

class MeasuredWidget extends StatefulWidget {
  final Function(Size? size) onCalculateSize;
  final Widget child;

  const MeasuredWidget({
    Key? key,
    required this.onCalculateSize,
    required this.child,
  }) : super(key: key);

  @override
  _MeasuredWidgetState createState() => _MeasuredWidgetState();
}

class _MeasuredWidgetState extends State<MeasuredWidget> {
  final key = GlobalKey();

  @override
  initState() {
    //calling the getHeight Function after the Layout is Rendered
    WidgetsBinding.instance?.addPostFrameCallback((_) => getHeight());

    super.initState();
  }

  void getHeight() {
    final size = key.currentContext?.size;
    widget.onCalculateSize(size);
  }

  @override
  Widget build(BuildContext context) {
    return _MeasuredWidgetContent(
      key: key,
      child: widget.child,
    );
  }
}

class _MeasuredWidgetContent extends HookWidget {
  final Widget child;
  const _MeasuredWidgetContent({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return child;
  }
}
```

**Comment by gorhom** [comment]
Could you guys test on ‘v4’ ? Thanks

**Comment by ktamir** [comment]
> Could you guys test on ‘v4’ ? Thanks

I had some issues with `v3`, tried `v4` with the new hook and it seems to work well
Thank you so much for the great work on this library!

**Comment by doougui** [comment]
For me scrollables with CONTENT_HEGIHT still aren't working

My code is looking like this:

```js
interface ContentHeightBottomSheetProps {
  children: any;
  bottomSheetModalRef: React.MutableRefObject<BottomSheetModalMethods>;
  initialSnapPoints?: (string | number)[];
  allowClosingOnPanDown?: boolean;
}

export function ContentHeightBottomSheet({ 
  children, 
  bottomSheetModalRef, 
  initialSnapPoints = ['5%', 'CONTENT_HEIGHT'],
  allowClosingOnPanDown = true,
}: ContentHeightBottomSheetProps) {
  const snapPoints = React.useMemo(() => [...initialSnapPoints], []);

  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(snapPoints);

  return (
    <BottomSheetModal
      ref={bottomSheetModalRef}
      index={1}
      backdropComponent={BottomSheetBackdrop}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}
      enablePanDownToClose={allowClosingOnPanDown}
    >
      <BottomSheetScrollView onLayout={handleContentLayout}>
        {children}
      </BottomSheetScrollView>
    </BottomSheetModal>
  );
}
```

It works perfectly when the content doesn't cover 100%+ of the screen, but when it does I cannot scroll. Seems like [this](https://giters.com/gorhom/react-native-bottom-sheet/issues/496) is the same issue I am experiencing 

Note that I am using `BottomSheetScrollView`, but it still doesn't scroll at all

**Comment by doougui** [comment]
@gorhom Any updates on this? Tbh I don't really know if I am doing something I am not supposed to or if scrollables with content height are not available yet :/

Thanks in advance :)

**Comment by vitorsilvalima** [comment]
Hey guys, I was able to make the scrollable content to work by setting the `maxHeight` for the `BottomSheetScrollView` component


```tsx
import React, { useMemo, forwardRef, useCallback } from 'react'
import { Dimensions, ScrollView, StyleSheet } from 'react-native'
import RNBottomSheet, {
  useBottomSheetDynamicSnapPoints,
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetScrollView,
} from '@gorhom/bottom-sheet'

interface BottomSheetProps {
  children: React.ReactNode
  onClose(): void
}

const styles = StyleSheet.create({
  backgroundStyle: {
    backgroundColor: 'transparent',
  },
  handleIndicator: {
    backgroundColor: 'white',
  },
})

const { height } = Dimensions.get('window')
function CustomBottomSheet(
  { children, onClose }: BottomSheetProps,
  ref: React.Ref<RNBottomSheet>,
): React.ReactElement {
  const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], [])

  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints)

  const renderBackdrop = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        animatedIndex={animatedContentHeight}
        pressBehavior="close"
      />
    ),
    [],
  )

  return (
    <RNBottomSheet
      ref={ref}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}
      animateOnMount={false}
      onClose={onClose}
      backdropComponent={renderBackdrop}
      backgroundStyle={styles.backgroundStyle}
      handleIndicatorStyle={styles.handleIndicator}
      enablePanDownToClose
    >
      <BottomSheetScrollView
        onLayout={handleContentLayout}
        style={{ maxHeight: height * 0.9 }}
      >
        {children}
      </BottomSheetScrollView>
    </RNBottomSheet>
  )
}

```

**Comment by tambadiya** [comment]
I have many screen in same BottomSheet and also I use bottomsheet on map so how can I give dynamic height of all screens.?

**Comment by taiyrbegeyev** [comment]
> Hey guys, I was able to make the scrollable content to work by setting the `maxHeight` for the `BottomSheetScrollView` component
> 
> ```tsx
> import React, { useMemo, forwardRef, useCallback } from 'react'
> import { Dimensions, ScrollView, StyleSheet } from 'react-native'
> import RNBottomSheet, {
>   useBottomSheetDynamicSnapPoints,
>   BottomSheetBackdrop,
>   BottomSheetBackdropProps,
>   BottomSheetScrollView,
> } from '@gorhom/bottom-sheet'
> 
> interface BottomSheetProps {
>   children: React.ReactNode
>   onClose(): void
> }
> 
> const styles = StyleSheet.create({
>   backgroundStyle: {
>     backgroundColor: 'transparent',
>   },
>   handleIndicator: {
>     backgroundColor: 'white',
>   },
> })
> 
> const { height } = Dimensions.get('window')
> function CustomBottomSheet(
>   { children, onClose }: BottomSheetProps,
>   ref: React.Ref<RNBottomSheet>,
> ): React.ReactElement {
>   const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], [])
> 
>   const {
>     animatedHandleHeight,
>     animatedSnapPoints,
>     animatedContentHeight,
>     handleContentLayout,
>   } = useBottomSheetDynamicSnapPoints(initialSnapPoints)
> 
>   const renderBackdrop = useCallback(
>     (props: BottomSheetBackdropProps) => (
>       <BottomSheetBackdrop
>         {...props}
>         animatedIndex={animatedContentHeight}
>         pressBehavior="close"
>       />
>     ),
>     [],
>   )
> 
>   return (
>     <RNBottomSheet
>       ref={ref}
>       snapPoints={animatedSnapPoints}
>       handleHeight={animatedHandleHeight}
>       contentHeight={animatedContentHeight}
>       animateOnMount={false}
>       onClose={onClose}
>       backdropComponent={renderBackdrop}
>       backgroundStyle={styles.backgroundStyle}
>       handleIndicatorStyle={styles.handleIndicator}
>       enablePanDownToClose
>     >
>       <BottomSheetScrollView
>         onLayout={handleContentLayout}
>         style={{ maxHeight: height * 0.9 }}
>       >
>         {children}
>       </BottomSheetScrollView>
>     </RNBottomSheet>
>   )
> }
> ```

This approach seemed to work but the bottom sheet start crashing after opening it multiple times. Is there a way to fix it?

**Comment by milosjovancevic** [comment]
> @nandorojo yes! it is available for `v2` & `v3`, look at the example [Dynamic Snap Point Example](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/DynamicSnapPointExample.tsx).

Hey is there anywhere example because this link is broken. I am struggling with animating sheet to match height of children.
Thanks

**Comment by exzos28** [comment]
> Hey guys, I was able to make the scrollable content to work by setting the `maxHeight` for the `BottomSheetScrollView` component
> 
> ```tsx
> import React, { useMemo, forwardRef, useCallback } from 'react'
> import { Dimensions, ScrollView, StyleSheet } from 'react-native'
> import RNBottomSheet, {
>   useBottomSheetDynamicSnapPoints,
>   BottomSheetBackdrop,
>   BottomSheetBackdropProps,
>   BottomSheetScrollView,
> } from '@gorhom/bottom-sheet'
> 
> interface BottomSheetProps {
>   children: React.ReactNode
>   onClose(): void
> }
> 
> const styles = StyleSheet.create({
>   backgroundStyle: {
>     backgroundColor: 'transparent',
>   },
>   handleIndicator: {
>     backgroundColor: 'white',
>   },
> })
> 
> const { height } = Dimensions.get('window')
> function CustomBottomSheet(
>   { children, onClose }: BottomSheetProps,
>   ref: React.Ref<RNBottomSheet>,
> ): React.ReactElement {
>   const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], [])
> 
>   const {
>     animatedHandleHeight,
>     animatedSnapPoints,
>     animatedContentHeight,
>     handleContentLayout,
>   } = useBottomSheetDynamicSnapPoints(initialSnapPoints)
> 
>   const renderBackdrop = useCallback(
>     (props: BottomSheetBackdropProps) => (
>       <BottomSheetBackdrop
>         {...props}
>         animatedIndex={animatedContentHeight}
>         pressBehavior="close"
>       />
>     ),
>     [],
>   )
> 
>   return (
>     <RNBottomSheet
>       ref={ref}
>       snapPoints={animatedSnapPoints}
>       handleHeight={animatedHandleHeight}
>       contentHeight={animatedContentHeight}
>       animateOnMount={false}
>       onClose={onClose}
>       backdropComponent={renderBackdrop}
>       backgroundStyle={styles.backgroundStyle}
>       handleIndicatorStyle={styles.handleIndicator}
>       enablePanDownToClose
>     >
>       <BottomSheetScrollView
>         onLayout={handleContentLayout}
>         style={{ maxHeight: height * 0.9 }}
>       >
>         {children}
>       </BottomSheetScrollView>
>     </RNBottomSheet>
>   )
> }
> ```

`contentHeight={animatedContentHeight}` - with this line i am getting incorrect content height on android

**Comment by quicksilverr** [comment]
> Hey guys, I was able to make the scrollable content to work by setting the `maxHeight` for the `BottomSheetScrollView` component
> 
> ```tsx
> import React, { useMemo, forwardRef, useCallback } from 'react'
> import { Dimensions, ScrollView, StyleSheet } from 'react-native'
> import RNBottomSheet, {
>   useBottomSheetDynamicSnapPoints,
>   BottomSheetBackdrop,
>   BottomSheetBackdropProps,
>   BottomSheetScrollView,
> } from '@gorhom/bottom-sheet'
> 
> interface BottomSheetProps {
>   children: React.ReactNode
>   onClose(): void
> }
> 
> const styles = StyleSheet.create({
>   backgroundStyle: {
>     backgroundColor: 'transparent',
>   },
>   handleIndicator: {
>     backgroundColor: 'white',
>   },
> })
> 
> const { height } = Dimensions.get('window')
> function CustomBottomSheet(
>   { children, onClose }: BottomSheetProps,
>   ref: React.Ref<RNBottomSheet>,
> ): React.ReactElement {
>   const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], [])
> 
>   const {
>     animatedHandleHeight,
>     animatedSnapPoints,
>     animatedContentHeight,
>     handleContentLayout,
>   } = useBottomSheetDynamicSnapPoints(initialSnapPoints)
> 
>   const renderBackdrop = useCallback(
>     (props: BottomSheetBackdropProps) => (
>       <BottomSheetBackdrop
>         {...props}
>         animatedIndex={animatedContentHeight}
>         pressBehavior="close"
>       />
>     ),
>     [],
>   )
> 
>   return (
>     <RNBottomSheet
>       ref={ref}
>       snapPoints={animatedSnapPoints}
>       handleHeight={animatedHandleHeight}
>       contentHeight={animatedContentHeight}
>       animateOnMount={false}
>       onClose={onClose}
>       backdropComponent={renderBackdrop}
>       backgroundStyle={styles.backgroundStyle}
>       handleIndicatorStyle={styles.handleIndicator}
>       enablePanDownToClose
>     >
>       <BottomSheetScrollView
>         onLayout={handleContentLayout}
>         style={{ maxHeight: height * 0.9 }}
>       >
>         {children}
>       </BottomSheetScrollView>
>     </RNBottomSheet>
>   )
> }
> ```

Hey @vitorsilvalima  Please could you explain, why does this work? making this maxHeight * 0.9 does what?

**Comment by bryanprimus** [comment]
is this feature available already? i don't see any in the docs.

I have tried this https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints

but it doesn't work with `BottomSheetScrollView`

also, i use this [example](https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints)

and it doesn't work well with `footerComponent` prop

**Comment by norbusonam** [comment]
I am confused on this as well, `CONTENT_HEIGHT` is being rejected for me

**Comment by ororsatti** [comment]
Seems like scrollable + dynamically sized container is a big request around here. 
Help me push it to @gorhom !
Here is the discussion I started about implementing it, TL;DR - its working!
https://github.com/gorhom/react-native-bottom-sheet/discussions/1363

**Comment by ororsatti** [comment]
Just sharing here that there is a PR ready for this exact feature.

#1402

**Comment by Eli-Nathan** [comment]
The solution I opted for with a dynamic snap point bottom sheet with max height is:

```ts
// ....
const initialSnapPoints = useMemo(() => ["CONTENT_HEIGHT"], [])
const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
} = useBottomSheetDynamicSnapPoints(initialSnapPoints)

const maxHeightStyle = useBottomSheetMaxHeight(maxHeight)

return (
    <BottomSheetModal
        // .... other props
        snapPoints={animatedSnapPoints as any}
        handleHeight={animatedHandleHeight}
        contentHeight={animatedContentHeight}
    >
        <BottomSheetScrollView
            onLayout={handleContentLayout}
            style={{
                maxHeight: maxHeightStyle,
            }}
        >
            {children}
        </BottomSheetScrollView>
    </BottomSheetModal>
)
// ...
```

With the custom `useBottomSheetMaxHeight` hook looking like this:

```ts
/*
    Designed to take the specified max height, take away top safe
    area inset and convert to a decimal
*/
import { useWindowDimensions } from "react-native"
import { useSafeAreaInsets } from "react-native-safe-area-context"

export const useBottomSheetMaxHeight = (maxHeight = "85%"): number => {
    const { height: deviceHeight } = useWindowDimensions()
    const maxHeightDecimal = parseFloat(`${maxHeight}`) / 100.0
    const { top: topSafeAreaInset } = useSafeAreaInsets()

    return (deviceHeight - topSafeAreaInset) * maxHeightDecimal
}

```

Hope that helps someone 😄

**Comment by puniker** [comment]
And now that the function useBottomSheetDynamicSnapPoints() becomes deprecated? There is no documentation about it...

**Comment by puniker** [comment]
> The solution I opted for with a dynamic snap point bottom sheet with max height is:
> 
> ```ts
> // ....
> const initialSnapPoints = useMemo(() => ["CONTENT_HEIGHT"], [])
> const {
>     animatedHandleHeight,
>     animatedSnapPoints,
>     animatedContentHeight,
>     handleContentLayout,
> } = useBottomSheetDynamicSnapPoints(initialSnapPoints)
> 
> const maxHeightStyle = useBottomSheetMaxHeight(maxHeight)
> 
> return (
>     <BottomSheetModal
>         // .... other props
>         snapPoints={animatedSnapPoints as any}
>         handleHeight={animatedHandleHeight}
>         contentHeight={animatedContentHeight}
>     >
>         <BottomSheetScrollView
>             onLayout={handleContentLayout}
>             style={{
>                 maxHeight: maxHeightStyle,
>             }}
>         >
>             {children}
>         </BottomSheetScrollView>
>     </BottomSheetModal>
> )
> // ...
> ```
> 
> With the custom `useBottomSheetMaxHeight` hook looking like this:
> 
> ```ts
> /*
>     Designed to take the specified max height, take away top safe
>     area inset and convert to a decimal
> */
> import { useWindowDimensions } from "react-native"
> import { useSafeAreaInsets } from "react-native-safe-area-context"
> 
> export const useBottomSheetMaxHeight = (maxHeight = "85%"): number => {
>     const { height: deviceHeight } = useWindowDimensions()
>     const maxHeightDecimal = parseFloat(`${maxHeight}`) / 100.0
>     const { top: topSafeAreaInset } = useSafeAreaInsets()
> 
>     return (deviceHeight - topSafeAreaInset) * maxHeightDecimal
> }
> ```
> 
> Hope that helps someone 😄

and now that the function useBottomSheetDynamicSnapPoints() becomes deprecated? There is no documentation about it

**Comment by Eli-Nathan** [comment]
> and now that the function useBottomSheetDynamicSnapPoints() becomes deprecated? There is no documentation about it

@puniker 
General docs are [here](https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints) but it is not yet deprecated. It will likely be deprecated in v5 which is still in Alpha. When the V5 docs are released it will hopefully just not include that section at all.

When using the hooks, your IDE should show the [JSDoc annotation](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/hooks/useBottomSheetDynamicSnapPoints.ts#L20) to inform you that it will soon be deprecated.

**Comment by alitsvin** [comment]
One can try to use `enableDynamicSizing` prop

**Comment by mustapha-ghlissi** [comment]
Please refer to this comment: 
https://github.com/gorhom/react-native-bottom-sheet/pull/1513#issuecomment-2154433013

**Comment by jrhager84** [comment]
Is there a way to dynamically set the height of the child scrollview based on the 'available' height rather than have the sheet react to the child's height? For instance. I have a list of 1000 items (which will overflow no matter what). However - I have 2 snap points where the sheet is half open (making the scroll view only take up 50% of the height) or 100%. The sheet seems to overflow off of the screen - Taking 100% of the height but only showing the top half (which doesn't work for scrollables). Am I doing something wrong? How would one handle that situation?

**Comment by indapublic** [comment]
@jrhager84 Same question

```
snapPoints={["50%", "96%"]}
```

**For 50%:**
<img width="391" alt="Image" src="https://github.com/user-attachments/assets/b08c25b8-3562-4d48-a31f-ec0cb3a473e6" />

**For 96%:**
<img width="368" alt="Image" src="https://github.com/user-attachments/assets/c1983e38-1f42-4a7e-b17c-dcb57f0fe80c" />
