### ISSUE TITLE
BottomSheetTextInput that has multiline enabled, does not push bottom sheet up when focused and keyboard shows.

### ISSUE THREAD

**Issue by jonesaustindev** [gorhom/react-native-bottom-sheet#411]
# Bug
BottomSheetTextInput that has multiline enabled, does not push bottom sheet up when focused and keyboard shows. If I remove the ability to have multiline enabled, it works as expected with no issue.

https://user-images.githubusercontent.com/36755092/115439911-b662d080-a1d4-11eb-96e7-8a5fad951076.mov

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | "^3.6.3"   |
| react-native                    | "0.63.4"  |
| react-native-reanimated         | "^2.0.0"   |
| react-native-gesture-handler    | "^1.9.0"  |

## Steps To Reproduce
Setting up a simple implementation of the `BottomSheetModal` will show how it behaves.

1. Make one `BottomSheetTextInput` have multiline while the other does not.
2. Tap the one without `multiline` to see it function correctly.
3. Tap the one with `multiline` to see it does not slide up the bottom sheet.

Describe what you expected to happen:

1. Keyboard should push up the bottom sheet when using `BottomSheetTextInput` with `multiline` enabled.

## Reproducible sample code
Note: This is inside a wrapper component that just has data/state management with a `View` with the style `{{ flex: 1, justifyContent: 'center', alignItems: 'center' }}`.
```
import React, { useContext, useMemo, useRef } from 'react';
import { StyleSheet, ScrollView, TouchableOpacity, Platform } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/core';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
  BottomSheetBackdrop,
  BottomSheetTextInput,
  BottomSheetScrollView,
} from '@gorhom/bottom-sheet';

import { Text } from '../components/common/Text';
import { View } from '../components/common/View';
import { Button } from '../components/common/Button';
import { ReorderIcon } from '../assets/svg/ReorderIcon';
import { ACTIVE_OPACITY } from '../constants';
import { localizedStrings } from '../localization/localizedStrings';
import { colors, globalStyles, SCREEN_HEIGHT, SCREEN_WIDTH } from '../styles/globalStyles';
import { GradientFooter } from '../components/common/GradientFooter';
import { HorizontalLine } from '../components/common/HorizontalLine';

export const ListScreen: React.FC<{}> = () => {
  const { top, bottom } = useSafeAreaInsets();
  const { goBack } = useNavigation();
  const buttonMargin = Platform.OS === 'ios' ? bottom - 8 : bottom + 16;

  const sheetRef = useRef<BottomSheetModal>(null);
  const snapPoints = useMemo(() => ['35%'], []);

  const handleShowPress = () => {
    sheetRef.current && sheetRef.current.present();
  };

  return (
  <>
      <ScrollView
        style={[styles.container, { paddingTop: top + globalStyles.standardPadding * 2 }]}
      >
        <View style={styles.header}>
          <TouchableOpacity
            // TODO re-order feature
            onPress={() => {}}
            activeOpacity={ACTIVE_OPACITY}
            style={styles.rightAlign}
          >
            <ReorderIcon />
          </TouchableOpacity>
          <View style={styles.center}>
            <View style={styles.button} marginVertical={globalStyles.screenPadding}>
              <Button
                fontSize={14}
                title={'+ Add to List'}
                onPress={handleShowPress}
              />
            </View>
          </View>
        </View>
      </ScrollView>
      <GradientFooter style={styles.center}>
        <TouchableOpacity
          hitSlop={{ left: 30, right: 30 }}
          activeOpacity={ACTIVE_OPACITY}
          onPress={goBack}
        >
          <Text fontSize={14} style={{ marginTop: buttonMargin }} fontFamily="americaBold">
            {localizedStrings.labels.back}
          </Text>
        </TouchableOpacity>
      </GradientFooter>
      <BottomSheetModalProvider>
        <BottomSheetModal
          ref={sheetRef}
          snapPoints={snapPoints}
          keyboardBehavior="interactive"
          keyboardBlurBehavior="restore"
          handleComponent={null}
          backdropComponent={BottomSheetBackdrop}
          style={{ ...globalStyles.shadow }}
        >
          <BottomSheetScrollView style={[styles.cardContent, { paddingBottom: bottom * 4 }]}>
            <BottomSheetTextInput
              placeholder="Add title"
              placeholderTextColor={colors.grey}
              style={styles.text}
              accessibilityComponentType
              accessibilityTraits
            />
            <HorizontalLine width={'100%'} />
            <BottomSheetTextInput
              placeholder="Add more details"
              placeholderTextColor={colors.grey}
              style={styles.text}
              multiline
              accessibilityComponentType
              accessibilityTraits
            />
          </BottomSheetScrollView>
        </BottomSheetModal>
      </BottomSheetModalProvider>
  </>
  );
};

const styles = StyleSheet.create({
  absolute: {
    position: 'absolute',
  },
  bottom: {
    ...globalStyles.shadow,
    paddingTop: globalStyles.standardPadding,
    padding: globalStyles.screenPadding,
  },
  button: {
    width: 170,
  },
  cardContent: {
    padding: globalStyles.screenPadding,
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: globalStyles.screenPadding,
  },
  image: {
    width: '100%',
    position: 'absolute',
  },
  rightAlign: {
    alignSelf: 'flex-end',
  },
  text: {
    paddingVertical: globalStyles.standardPadding * 2,
  },
```

**Comment by jonesaustindev** [comment]
I've also noticed that Android doesn't seem to scroll inside. I might be missing something though since that should work.

**Comment by marcibk** [comment]
Any news with this? :)

**Comment by VithuJey** [comment]
Any update on BottomSheetTextInput with multiline?

**Comment by VithuJey** [comment]
@jonesaustindev Did you find any way?

**Comment by VithuJey** [comment]
@gorhom Can you please look into this?

**Comment by theianjohnson** [comment]
@gorhom Also having this issue, snack with the multiline bug https://snack.expo.io/@setjetters/excited-french-fries

**Comment by Vitaliy-Pankov-Kernelics** [comment]
Same here. Can confirm that the issue is caused by **multiline={true}** and as soon as I disable it, keyboard starts working as expected. The issues is that the inner implementation of **BottomSheetTextInput** is pretty straightforward and it just sets whether bottom sheet should handle keyboard events or not. I'm really confused and it is a good question, _where_ to fix it, because it doesn't really look like we can blame **BottomSheetTextInput** here

**Comment by Vitaliy-Pankov-Kernelics** [comment]
It would be great to reopen the issue, because it is clearly there and needs fixing

**Comment by armanian** [comment]
Same here :(

**Comment by anhquan291** [comment]
Facing the same problem. Any solutions yet guys? Thank you

**Comment by dickfickling** [comment]
I don't have a solution, but I've narrowed it down. With single line text inputs, the `onFocus` handler is reliably called before the `keyboardWillShow` event. In `handleKeyboardEvent`, the code expects that `shouldHandleKeyboardEvents` has been set to `true` by the `onFocus` handler. If it's false, it doesn't update the keyboard height/visibility state, and therefore doesn't move the view.

When `multiline` is set to true, the `keyboardWillShow` handler executes before `onFocus`, so `shouldHandleKeyboardEvents` is false, and none of the views are updated.

I'm not really sure why `shouldHandleKeyboardEvents` is needed in the first place. Perhaps it's a performance tweak? Removing all references to it fixes this bug and everything else _seems_ to continue working, but maybe there's an edge case I'm missing.

@gorhom would you mind reopening this issue?

**Comment by gorhom** [comment]
Hi everyone, sorry for the delay, this issue is resolved for `v4` and it will release on `4.0.0-alpha.25` 👍

**Comment by dickfickling** [comment]
:heart: thank you @gorhom!

**Comment by jonesaustindev** [comment]
Awesome, thank you @gorhom!

**Comment by melissa07** [comment]
Does anybody still have an issue ? I'm on version 4.5.1 and it still doesn't work for me.

**Comment by SyedTayyabUlMazhar** [comment]
@gorhom It still doesn't seem to work, could you please look into this.

**Comment by bim-oulabi** [comment]
Yes please, using 4.6.1 and it doesnt work on multiline inputs

**Comment by aldebout** [comment]
Same on v5, removing `multiline` fixes it immediately.

**Comment by benjaminharringtonrose** [comment]
Same here - seeing the issue now on the latest version (5.0.6)

**Comment by piotr-graczyk-dev** [comment]
Still relevant in version 5.0.6. 

While waiting for the changes in the package, I came up with a quick solution to the problem, which for my need was a solution. Let me know if it helped you and I look forward for a better solution 😄 

```
import {
  BottomSheetModal,
  BottomSheetScrollView,
  BottomSheetScrollViewMethods,
  BottomSheetTextInput,
} from '@gorhom/bottom-sheet';
import React, { useRef } from 'react';

export const BottomSheetWithMultilineTextInput = () => {
  const scrollViewRef = useRef<BottomSheetScrollViewMethods>(null);

  return (
    <BottomSheetModal snapPoints={['100%']} keyboardBlurBehavior="restore">
      <BottomSheetScrollView
        ref={scrollViewRef}
        onContentSizeChange={() => {
          scrollViewRef.current?.scrollToEnd({
            animated: true,
          });
        }}>
        <BottomSheetTextInput multiline />
      </BottomSheetScrollView>
    </BottomSheetModal>
  );
};

```

**Comment by codingslash76** [comment]
@gorhom 
This issue should be reopened, as we are still experiencing it with the latest version.

Without Multiline.
https://github.com/user-attachments/assets/13d7d51a-ccfe-45f2-bdfe-46018db1a316

https://github.com/user-attachments/assets/b6a07150-5745-44bd-b229-cbccfecbf706

Multiline Enabled.
https://github.com/user-attachments/assets/065ba87c-a331-4559-9fc3-e0503dd0ff74

https://github.com/user-attachments/assets/c76f9dfe-18dc-4274-b6c0-ec75b7717026

`<BottomSheetTextInput
    numberOfLines={3}
    textAlignVertical={'top'}
    style={{flex: 1, height: 100, borderRadius: 8, alignItems: 'flex-start', textAlignVertical: 'top', paddingTop: 0}}
    multiline
    ....
/>`

**Comment by Dani2601** [comment]
Any other solutions? I'm still experiencing the issue.

**Comment by alanlwl** [comment]
Still experiencing the issue in version 5.2.6

**Comment by KJ-GM** [comment]
same issue here. any relevant solution ?

**Comment by Mavludin** [comment]
A workaround is to use [BottomSheetKeyboardAwareScrollView](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/components/keyboard-aware-scroll-view#gorhombottom-sheet) with the `extraKeyboardSpace` prop

**Comment by bjornhansen** [comment]
I'm still seeing this bug in version 5.2.8. In Expo when on iOS.
